### PR TITLE
Improve error handling in updateValues()

### PR DESCRIPTION
**Pull request by rudders**
Not as elegant as I would have liked but ensures the updateValues function completes even if the DOM doesn't include some of the items that are defined in the config.

### CODE REVIEW

**Comment by rudders** [comment]
My GIT skills are wanting - looks like a lot of work for a few minor changes....

**Comment by DavidFW1960** [comment]
Ok... lets give that a run.
You seemed to indicate in the PR you closed that you had some problems?

This is a bastard how this works actually.. I have waste days this week trying to fix a few things... I never realised that defining an entity and then not using it would screw things up so badly.

Thanks for your great work on this. I'll merge this and run it overnight and then push a new one tomorrow....

**Comment by rudders** [comment]
No worries - I reckon a refactor is in order to try and simplify the logic a bit.
I really wanted to drop the if statements in the updateValues function and simply use to try to update what was available bu the beauford and one other field seem to have spans with id's there all the time even when they are not used.

Rather than try and work around that I just protected the function from getElementById function that errored - but of a blunt instrument....

(the original) module should probably put the html into the right slots and then have one function to update whatever is there..... but hacking away at it will probably satisfy the needs of Aussie HA users.

**Comment by DavidFW1960** [comment]
Yeah. The Beaufort one.... PITA. I didn't allow that if using knots because then I would need to convert from knots to get the Beaufort number as it's converting the regular wind speed (km/h)

The refactor you describe is most probably a good idea but above my pay grade lol... I am just a hacker although not sure how much original code is left now lol.

Anyway thanks again.

**Comment by DavidFW1960** [comment]
Hey...
I just added Beaufort back in and I also allowed it for the knots variant..
I am not 100% sure it's working. There is no wind at all right now.
If you get a chance can you check I didn't screw up the variables or anything stupid like that? Thanks.

**Comment by DavidFW1960** [comment]
fixed the bastard! Woot.

**Pull request merged**
