### PR TITLE
Fix periodic updating of states.

### PR DESCRIPTION
**Pull request by rudders**
Removed reference to ```popunit``` which caused the code following to never execute.
Small typo in first run of update code.
Needed to fox this for my Kiosk

### CODE REVIEW

**Comment by DavidFW1960** [comment]
popunit is defined on line 118
you're right about pos containing it though

**Comment by DavidFW1960** [comment]
I thought is was something to do with this.
image
I had a devil of a job getting the mm on the end to not change size when the card refreshed.
I have merged this as it seems to be ok.
I'll push a new release soon. If you're using HACS you can load from master..
Thanks.

**Comment by rudders** [comment]
It's defined in a different scope I think so not available - but seems unnecessary... 
I've "fixed" it locally for now so no hurry with a HACS release.

**Comment by DavidFW1960** [comment]
> It's defined in a different scope I think so not available

you're almost certainly correct. Honestly I'm just a hacker with a growing but incomplete understanding of WTF I am doing. I really appreciate your help. I will delete that variable now as it's not referenced anywhere else.
Thanks.

**Comment by DavidFW1960** [comment]
Shows this when it refreshes
image
Instead of:
image

**Comment by DavidFW1960** [comment]
I *might* have fixed that..

**Comment by rudders** [comment]
Oh. Haven't seen that behaviour - I'll keep monitoring it. Maybe I don't have gusts turned on - I think that's an option isn't it.

**Comment by DavidFW1960** [comment]
yes if you don't parse through the gusts to the card they don't display.
This is very similar to the issue I was having with the rainfall one way back. I seem to have fixed it and also removed the leading zero from sun times if using 12Hr.
If you wouldn't mind pulling master in HACS and maybe adding in wind gusts to help me check I haven't broken anything else that would be most helpful. I just updated the version to report 0.59 as well just now. I always forget that bit.

**Comment by rudders** [comment]
Grabbed the latest version from Gitub.... and added Gust in - will keep an eye on it.

**Comment by rudders** [comment]
possible_today in a slot seems to be a dependency now - without it the module breaks in the slotValue function without it. Just FYI.

**Comment by DavidFW1960** [comment]
not 100% sure what you mean?
If you configure a slot to show something (like possible_today) If you are not parsing that through to the card from Lovelace the card won't display. But that is true for all slots. Or am I misunderstanding what you are saying?

**Comment by DavidFW1960** [comment]
I just commented out my possible_today from lovelace and it didn't cause a problem

**Pull request merged**
