### PR TITLE
Simplify update / Refresh function

### PR DESCRIPTION
**Pull request by rudders**
This is a different approach - happy for you to ignore but seemed to simplify the logic to my mind - if the function just trys to update everything but ignores any failures the function always complete and everything that can be updated is. 

This disconnect the logic that if a source for an attribute is defined it has to be used or the function fails at that point which in turn means nothing else gets updated.

### CODE REVIEW

**Comment by DavidFW1960** [comment]
So.... branch has conflicts that must be resolved? Did you do your edits after mine?
Happy to merge this but I can't as it stands..

**Comment by rudders** [comment]
Found a problem - will get back to you.

**Comment by DavidFW1960** [comment]
just so you know, I updated again today and added a precipitation rate (mm/h) option that was originally in the card but I butchered back when I didn't have the slightest clue what I was doing (moreso than today LOL)
I also had a request to allow knots as a unit instead of km/h which I just said no but I'm considering allowing it as it's possibly not too difficult. What say you?

**Comment by DavidFW1960** [comment]
actually on line 115 where I define wind, I have:
<span id="wind-gust-text"> (Gust ${this.current.windGust}</span>
so on line 857 I have no idea WHY I had to include (Gust to fix the refresh problem for that element like:
```
      if (this.config.entity_wind_gust && !this.config.alt_wind) { root.getElementById("wind-gust-text").textContent = ` (Gust ${this.current.windGust}` }
```
Which will make it hard to use knots.

**Comment by DavidFW1960** [comment]
I just added a new slot option for knots.

**Comment by DavidFW1960** [comment]
So... I think I am seeing the problem you mentioned.
I am finding that sometimes an error gets thrown (well on every refresh) For instance if I don't have pressure configured in a slot but it is parsed through to the card anyway it throws an error and as you said stops processing.
So did you work out the error you were having with this?

**Comment by DavidFW1960** [comment]
also with my latest code:
It refreshes but the wind bearing is not the same for both??
image

**Comment by rudders** [comment]
Yep - my try/catch code tests out pretty well - you moved the code on so I haven't got back to it - I'll do you a PR based on your current repo if you like.

**Comment by DavidFW1960** [comment]
just pushed an update now...
so give it a few for your PR
I think I'm going to have to make another variable for the wind direction for knots
I'll wait till you push your PR

**Comment by DavidFW1960** [comment]
ok I got the wind direction working for both by creating another variable. just pushed now

**Comment by rudders** [comment]
Oh - righto - will start with latest.

**Pull request closed without merging**
