### PR TITLE
Fix daily-summary-text refresh

### PR DESCRIPTION
**Pull request by rudders**
Realised I should have added some testing here... apologies for the multiple attempts but this lit-html templating is doing my head in... and also don't create PRs before 7am....

### CODE REVIEW

**Comment by DavidFW1960** [comment]
Bloody hell!!!! hahahaha. I just pushed an update as well before I saw this. Bugger.

**Comment by DavidFW1960** [comment]
So if I'm reading this correctly, the only changes from my latest are you added an ID to the div class on line 71 and you added logic for the UV and fire danger refreshes on lines 867-872?

I will just run this for a little before I push 0.70!

**Comment by rudders** [comment]
Yeah I know - a lot of activity for 4 lines of code!!

**Comment by DavidFW1960** [comment]
Just checking I didn't miss anything with the cross merging etc..... Looking good so far anyway.

**Comment by rudders** [comment]
And to add to my fun it looks like the BOM has blacklisted my ip address!! Can't ping either of their IP addresses and even www.bom.gov.au is slow. none of my apps on my phones can get to the BOM data..... wonder if it'll unblock itself. Don't want to have to get Telstra to reset my fixed WAN IP!

**Comment by DavidFW1960** [comment]
I think there might be some kind of rate limit. I seem to remember that's why Brendan wrote that FTP component but that doesn't help with observations.
You can try changing the scan interval on the HA BOM sensor.. I seem to remember I did that.

**Comment by DavidFW1960** [comment]
So I wonder if you wouldn't mind looking at something for me?
The Pos... default slot R1
image
The rain today is not refreshing automatically.
I have had a bit of a look and I saw a duplicate id I had used.. fixed that but it's not working.
I don't seem to be able to crack it at this point. Maybe you can help me?

**Comment by rudders** [comment]
Sure... I'll take a look.

**Comment by DavidFW1960** [comment]
I think I might have fixed it... have a look around line 862. I remember when I first forked this card that this gave me all sorts of problems.. but I might have fixed it

**Comment by rudders** [comment]
Yep found it too - didn't actually update textContent. I'm trying to catch errors and ignore them to make the card mre stable - I frequently remove an item from a slot but leave the parameter in the card which cases it to error out of the update function early - have been testing it and seems to work as per the following Line 862!
```
if (this.config.entity_pop_intensity && !this.config.alt_pop) {try {root.getElementById("intensity-text").textContent = ` - ${this._hass.states[this.config.entity_pop_intensity].state}` } catch(e) {}} 
```

**Comment by DavidFW1960** [comment]
yeah so almost identical to mine. I found including the ` - ` in the last bit didn't work.
the shit of it is you need to manually set the state for the intensity and keep hammering it for about a minute of the ftp component will zero it out again.

I don't mind the 'error' when a slot is defined and missing - that's not something most people will do all the time and it's obvious when troubleshooting (from my end) as the card doesn't display and the reason is always that an entity is missing.


> I frequently remove an item from a slot but leave the parameter in the card which cases it to error out of the update function early

not 100% what you mean here of if it's different to my above comment?

**Comment by DavidFW1960** [comment]
not getting the error with the bit that didn't work now...

**Comment by rudders** [comment]
My issue was that if you defined a source for an attribute and didn't use the attribute the code would error but not throw an error to the console or the UI - it's just failed and the update function returned without completing the rest of the function - I have a PR I'll make for you to consider.

**Comment by DavidFW1960** [comment]
Ok now I understand... but I maybe made and pushed an edit before your PR and I can't merge due to conflicts needing to be resolved...
I need to look at how to fix this and merge tomorrow.

**Pull request merged**
