### PR TITLE
Add error checks

### PR DESCRIPTION
**Pull request by Makin-Things**
This PR adds checks to stop .state of non-existent sensors being called and causing exceptions that blank the card.

### CODE REVIEW

**Comment by DavidFW1960** [comment]
What is the conflict here preventing merging?
Seems to be line 54??
```
<<<<<<< add-error-checks
          ${biggerIcon}
=======
          <span class="icon bigger" id="icon-bigger" style="background: none, url(${this._hass.hassUrl("/local/icons/weather_icons/" + (this.config.static_icons ? "static" : "animated") + "/" + this.weatherIcons[this.currentConditions] + ".svg")}) no-repeat; background-size: contain;">${this.currentConditions}</span>
>>>>>>> master
```
the ====== part?

**Comment by DavidFW1960** [comment]
Also with our discussion on versioning we should make it 1.1.0 right?

**Comment by Makin-Things** [comment]
I think that would be a fair call for this one.

**Comment by DavidFW1960** [comment]
Simon it was duplicating the span class at line 5x Not sure why...
Can you check the js file 'looks right'?
I also bumped the version as we mentioned above. I won't do the release until you confirm it looks ok.

**Pull request merged**
